/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("application")
    id("org.sonarqube") version "5.0.0.4638"
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    implementation(libs.guava)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    mainClass.set("org.example.App")
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}

sonar {
    properties {
        property("sonar.projectKey", "blowfish")
        property("sonar.organization", "mirija-712")
        property("sonar.host.url", "https://sonarcloud.io")
        property("sonar.login", System.getenv("SONAR_TOKEN"))
    }
}